const baseFoods = [
  {
    id: "ru_pelmeni_pork_beef",
    icon: "🥟",
    name: {
      ru: "Пельмени со свининой и говядиной",
      en: "Pork and beef pelmeni",
      zh: "猪肉牛肉俄式饺子",
      es: "Pelmeni con cerdo y ternera",
      fr: "Pelmeni au porc et au bœuf",
      de: "Pelmeni mit Schweine- und Rindfleisch",
      it: "Pelmeni con maiale e manzo",
      pt: "Pelmeni com porco e carne bovina",
      tr: "Domuz ve dana etli pelmeni",
      ar: "بيلميني بلحم الخنزير والبقر",
      ja: "豚肉と牛肉のペリメニ",
      ko: "돼지고기와 소고기 펠메니"
    },
    cuisine: {
      ru: "Русская кухня",
      en: "Russian cuisine",
      zh: "俄罗斯菜",
      es: "Cocina rusa",
      fr: "Cuisine russe",
      de: "Russische Küche",
      it: "Cucina russa",
      pt: "Cozinha russa",
      tr: "Rus mutfağı",
      ar: "المطبخ الروسي",
      ja: "ロシア料理",
      ko: "러시아 요리"
    },
    category: "dumplings",
    calories: 250,
    protein: 11,
    fat: 13,
    carbs: 23,
    aliases: ["пельмени", "pelmeni", "dumplings", "俄式饺子", "russian dumplings"]
  },
  {
    id: "cn_jiaozi_pork_cabbage",
    icon: "🥟",
    name: {
      ru: "Китайские пельмени со свининой и капустой",
      en: "Chinese pork and cabbage dumplings",
      zh: "猪肉白菜饺子",
      es: "Dumplings chinos con cerdo y col",
      fr: "Raviolis chinois au porc et au chou",
      de: "Chinesische Teigtaschen mit Schweinefleisch und Kohl",
      it: "Ravioli cinesi con maiale e cavolo",
      pt: "Dumplings chineses com porco e repolho",
      tr: "Domuz eti ve lahanalı Çin mantısı",
      ar: "زلابية صينية بلحم الخنزير والملفوف",
      ja: "豚肉と白菜の中国餃子",
      ko: "돼지고기와 배추 중국식 만두"
    },
    cuisine: {
      ru: "Китайская кухня",
      en: "Chinese cuisine",
      zh: "中国菜",
      es: "Cocina china",
      fr: "Cuisine chinoise",
      de: "Chinesische Küche",
      it: "Cucina cinese",
      pt: "Cozinha chinesa",
      tr: "Çin mutfağı",
      ar: "المطبخ الصيني",
      ja: "中華料理",
      ko: "중국 요리"
    },
    category: "dumplings",
    calories: 230,
    protein: 9,
    fat: 11,
    carbs: 24,
    aliases: ["饺子", "jiaozi", "dumplings", "китайские пельмени", "пельмени"]
  },
  {
    id: "cn_guotie",
    icon: "🥟",
    name: {
      ru: "Жареные китайские пельмени",
      en: "Chinese fried dumplings",
      zh: "锅贴",
      es: "Dumplings chinos fritos",
      fr: "Raviolis chinois grillés",
      de: "Gebratene chinesische Teigtaschen",
      it: "Ravioli cinesi fritti",
      pt: "Dumplings chineses fritos",
      tr: "Kızarmış Çin mantısı",
      ar: "زلابية صينية مقلية",
      ja: "焼き中国餃子",
      ko: "중국식 군만두"
    },
    cuisine: {
      ru: "Китайская кухня",
      en: "Chinese cuisine",
      zh: "中国菜",
      es: "Cocina china",
      fr: "Cuisine chinoise",
      de: "Chinesische Küche",
      it: "Cucina cinese",
      pt: "Cozinha chinesa",
      tr: "Çin mutfağı",
      ar: "المطبخ الصيني",
      ja: "中華料理",
      ko: "중국 요리"
    },
    category: "dumplings",
    calories: 260,
    protein: 9,
    fat: 14,
    carbs: 25,
    aliases: ["锅贴", "guotie", "fried dumplings", "жареные пельмени"]
  },
  {
    id: "jp_gyoza_pork",
    icon: "🥟",
    name: {
      ru: "Японские гёдза со свининой",
      en: "Japanese pork gyoza",
      zh: "日式猪肉煎饺",
      es: "Gyoza japonesa con cerdo",
      fr: "Gyoza japonais au porc",
      de: "Japanische Gyoza mit Schweinefleisch",
      it: "Gyoza giapponesi con maiale",
      pt: "Gyoza japonês com porco",
      tr: "Domuz etli Japon gyoza",
      ar: "غيوزا يابانية بلحم الخنزير",
      ja: "豚肉餃子",
      ko: "일본식 돼지고기 교자"
    },
    cuisine: {
      ru: "Японская кухня",
      en: "Japanese cuisine",
      zh: "日本菜",
      es: "Cocina japonesa",
      fr: "Cuisine japonaise",
      de: "Japanische Küche",
      it: "Cucina giapponese",
      pt: "Cozinha japonesa",
      tr: "Japon mutfağı",
      ar: "المطبخ الياباني",
      ja: "日本料理",
      ko: "일본 요리"
    },
    category: "dumplings",
    calories: 250,
    protein: 9,
    fat: 13,
    carbs: 24,
    aliases: ["гёдза", "gyoza", "餃子", "日式煎饺", "dumplings"]
  },
  {
    id: "kr_mandu_pork",
    icon: "🥟",
    name: {
      ru: "Корейские манду со свининой",
      en: "Korean pork mandu",
      zh: "韩式猪肉饺子",
      es: "Mandu coreano con cerdo",
      fr: "Mandu coréen au porc",
      de: "Koreanische Mandu mit Schweinefleisch",
      it: "Mandu coreani con maiale",
      pt: "Mandu coreano com porco",
      tr: "Domuz etli Kore mantısı",
      ar: "ماندو كوري بلحم الخنزير",
      ja: "韓国式豚肉マンドゥ",
      ko: "돼지고기 만두"
    },
    cuisine: {
      ru: "Корейская кухня",
      en: "Korean cuisine",
      zh: "韩国菜",
      es: "Cocina coreana",
      fr: "Cuisine coréenne",
      de: "Koreanische Küche",
      it: "Cucina coreana",
      pt: "Cozinha coreana",
      tr: "Kore mutfağı",
      ar: "المطبخ الكوري",
      ja: "韓国料理",
      ko: "한국 요리"
    },
    category: "dumplings",
    calories: 230,
    protein: 9,
    fat: 10,
    carbs: 26,
    aliases: ["манду", "mandu", "만두", "韩式饺子", "dumplings"]
  },
  {
    id: "ru_borscht_beef",
    icon: "🍲",
    name: {
      ru: "Борщ с говядиной",
      en: "Borscht with beef",
      zh: "牛肉罗宋汤",
      es: "Borsch con ternera",
      fr: "Bortsch au bœuf",
      de: "Borschtsch mit Rindfleisch",
      it: "Borscht con manzo",
      pt: "Borscht com carne bovina",
      tr: "Dana etli borş",
      ar: "بورش بلحم البقر",
      ja: "牛肉入りボルシチ",
      ko: "소고기 보르시"
    },
    cuisine: {
      ru: "Русская кухня",
      en: "Russian cuisine",
      zh: "俄罗斯菜",
      es: "Cocina rusa",
      fr: "Cuisine russe",
      de: "Russische Küche",
      it: "Cucina russa",
      pt: "Cozinha russa",
      tr: "Rus mutfağı",
      ar: "المطبخ الروسي",
      ja: "ロシア料理",
      ko: "러시아 요리"
    },
    category: "soup",
    calories: 85,
    protein: 4,
    fat: 4,
    carbs: 8,
    aliases: ["борщ", "borscht", "罗宋汤"]
  },
  {
    id: "it_spaghetti_bolognese",
    icon: "🍝",
    name: {
      ru: "Спагетти болоньезе",
      en: "Spaghetti bolognese",
      zh: "肉酱意大利面",
      es: "Espaguetis a la boloñesa",
      fr: "Spaghetti bolognaise",
      de: "Spaghetti Bolognese",
      it: "Spaghetti alla bolognese",
      pt: "Espaguete à bolonhesa",
      tr: "Bolonez soslu spagetti",
      ar: "سباغيتي بولونيز",
      ja: "スパゲッティ・ボロネーゼ",
      ko: "스파게티 볼로네제"
    },
    cuisine: {
      ru: "Итальянская кухня",
      en: "Italian cuisine",
      zh: "意大利菜",
      es: "Cocina italiana",
      fr: "Cuisine italienne",
      de: "Italienische Küche",
      it: "Cucina italiana",
      pt: "Cozinha italiana",
      tr: "İtalyan mutfağı",
      ar: "المطبخ الإيطالي",
      ja: "イタリア料理",
      ko: "이탈리아 요리"
    },
    category: "pasta",
    calories: 155,
    protein: 7,
    fat: 5,
    carbs: 21,
    aliases: ["спагетти", "болоньезе", "spaghetti", "bolognese", "pasta", "意大利面"]
  },
  {
    id: "es_paella_seafood",
    icon: "🥘",
    name: {
      ru: "Паэлья с морепродуктами",
      en: "Seafood paella",
      zh: "海鲜西班牙饭",
      es: "Paella de mariscos",
      fr: "Paella aux fruits de mer",
      de: "Paella mit Meeresfrüchten",
      it: "Paella ai frutti di mare",
      pt: "Paella de frutos do mar",
      tr: "Deniz ürünlü paella",
      ar: "باييلا بالمأكولات البحرية",
      ja: "シーフードパエリア",
      ko: "해산물 파에야"
    },
    cuisine: {
      ru: "Испанская кухня",
      en: "Spanish cuisine",
      zh: "西班牙菜",
      es: "Cocina española",
      fr: "Cuisine espagnole",
      de: "Spanische Küche",
      it: "Cucina spagnola",
      pt: "Cozinha espanhola",
      tr: "İspanyol mutfağı",
      ar: "المطبخ الإسباني",
      ja: "スペイン料理",
      ko: "스페인 요리"
    },
    category: "rice",
    calories: 160,
    protein: 8,
    fat: 5,
    carbs: 21,
    aliases: ["паэлья", "paella", "mariscos", "海鲜饭"]
  },
  {
    id: "in_chicken_curry",
    icon: "🍛",
    name: {
      ru: "Куриное карри",
      en: "Chicken curry",
      zh: "咖喱鸡",
      es: "Curry de pollo",
      fr: "Curry de poulet",
      de: "Hähnchencurry",
      it: "Curry di pollo",
      pt: "Caril de frango",
      tr: "Tavuk köri",
      ar: "كاري الدجاج",
      ja: "チキンカレー",
      ko: "치킨 커리"
    },
    cuisine: {
      ru: "Индийская кухня",
      en: "Indian cuisine",
      zh: "印度菜",
      es: "Cocina india",
      fr: "Cuisine indienne",
      de: "Indische Küche",
      it: "Cucina indiana",
      pt: "Cozinha indiana",
      tr: "Hint mutfağı",
      ar: "المطبخ الهندي",
      ja: "インド料理",
      ko: "인도 요리"
    },
    category: "curry",
    calories: 180,
    protein: 13,
    fat: 10,
    carbs: 9,
    aliases: ["карри", "chicken curry", "curry", "咖喱鸡", "pollo curry"]
  },
  {
    id: "mx_beef_tacos",
    icon: "🌮",
    name: {
      ru: "Тако с говядиной",
      en: "Beef tacos",
      zh: "牛肉塔可",
      es: "Tacos de ternera",
      fr: "Tacos au bœuf",
      de: "Rindfleisch-Tacos",
      it: "Tacos con manzo",
      pt: "Tacos de carne bovina",
      tr: "Dana etli taco",
      ar: "تاكو بلحم البقر",
      ja: "ビーフタコス",
      ko: "소고기 타코"
    },
    cuisine: {
      ru: "Мексиканская кухня",
      en: "Mexican cuisine",
      zh: "墨西哥菜",
      es: "Cocina mexicana",
      fr: "Cuisine mexicaine",
      de: "Mexikanische Küche",
      it: "Cucina messicana",
      pt: "Cozinha mexicana",
      tr: "Meksika mutfağı",
      ar: "المطبخ المكسيكي",
      ja: "メキシコ料理",
      ko: "멕시코 요리"
    },
    category: "street_food",
    calories: 220,
    protein: 12,
    fat: 11,
    carbs: 19,
    aliases: ["тако", "tacos", "taco", "塔可"]
  }
];
